name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # sudo required to unpack rootfs cpio with proper perms
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t tinycore:latest .
